### PR TITLE
Angular16 support

### PR DESCRIPTION
**Pull request by KristofGilis**

### CODE REVIEW

**Review by sankruthyas-kh — APPROVED** [review]

**Comment by Schloesslin** [comment]
Hi, when does this pull request will be merged ?

**Comment by KristofGilis** [comment]
@h2qutc

**Review by sankruthyas-kh — APPROVED** [review]

**Comment by e-knaake-covadis** [comment]
This could fix #324 
Any sight on a date this could be merged?

**Comment by mdtalel** [comment]
please merged!

**Comment by eSpVoLTaGe** [comment]
Would be awesome, waiting for it as well. :-)

**Comment by sideview1** [comment]
Are there other admins of this library to help merge/maintain it?

**Comment by WouterPtlVDP** [comment]
Is this package even maintained?

**Comment by h2qutc** [comment]
Hi @WouterPtlVDP , yes it is always maintained. I will work to release a new version supporting Angular 16 this weekend at the latest.

**Comment by saithis** [comment]
@h2qutc did you make any progress?

**Comment by Suneeh** [comment]
@h2qutc "this weekend" has been 2 weeks ago. Checking the comments, I feel like ~15 projects would love an updated version (or just a merged PR at this point).

**Comment by John-Santacruz** [comment]
Hi, may i know when the package will released?

**Comment by galvakojis** [comment]
could be "this weekend" at the latest. :D

**Comment by AlixRoyere** [comment]
Hello, any news? Is there an issue? 🤓

**Comment by Narsun** [comment]
And me...:)

**Comment by sQu1rr** [comment]
Still waiting. Maybe you should consider adding other maintainers?

**Comment by SergMoisCapital** [comment]
UP

**Comment by SergMoisCapital** [comment]
image
Author. 

Does anybody want to make a fork with this PR ?

**Comment by h2qutc** [comment]
Hi all, I'm working on this. I hope that one new version supporting Angular 16 will be released within 2 days max. I promise ;) 
Thanks all for your supporting.

**Comment by Suneeh** [comment]
> will be released within 2 days max. I promise ;)

See.. don't promise things if you don't do it..

**Comment by sideview1** [comment]
There is now 2 additional PRs for angular 16 upgrade (one opened 5 hours ago)... If anything just open this up to more people so it's not just you maintaining?

**Comment by h2qutc** [comment]
Hi all, a version v16.0.0 has been already released with support Angular 16 (https://www.npmjs.com/package/@angular-material-components/datetime-picker?activeTab=versions).
There will be certainly the issues, check it out and let me know if it works as expected.
Thank you all for your support.

**Comment by h2qutc** [comment]
@Suneeh  You are right 😃. Anyway, I could fortunately finish the promise.

**Comment by Narsun** [comment]
> Hi all, a version v16.0.0 has been already released with support Angular 16 (https://www.npmjs.com/package/@angular-material-components/datetime-picker?activeTab=versions). There will be certainly the issues, check it out and let me know if it works as expected. Thank you all for your support.

thank you!

**Comment by amin-setayeshfar** [comment]
@h2qutc Hi! thank you for the new version. :-)
in the last version `ngxMatDatetimeInput` is no longer available

**Comment by h2qutc** [comment]
@amin-setayeshfar  Can you try to use NgxMatDatepickerInput instead ?

**Comment by amin-setayeshfar** [comment]
> @amin-setayeshfar Can you try to use **ngxMatDatepickerInput** instead ?

thanks for the quick help,
well i had this component that implements ControlValueAccessor built around ngx-mat-datetime-picker and I have been using this to update my control value
`
    this.ngxMatDatetimeInput._valueChange
      .pipe(takeUntil(this.destroyed$))
      .subscribe((value: D) => this.onChange(value));`
 I also tried using `NgxMatDatepickerInput` instead of `ngxMatDatetimeInput` but then:
`Property '_valueChange' does not exist on type 'NgxMatDatepickerInput<D>'`

**Comment by eSpVoLTaGe** [comment]
After Upgrading (Angular 16 and "@angular-material-components/datetime-picker": "^16.0.0"" i am facing the problem, that the picker is not working as before. The Size of the picker is way too large and the stylings are terribly wrong.
Functionalities like min and max are not working either.

(Same Problem on https://h2qutc.github.io/angular-material-components/#/datetimepicker -> Examples -> TouchUi set to true)

`
        <mat-form-field appearance="outline">
          <mat-label>Reservierungsstartzeit</mat-label>
          <input (dateChange)="startChanged($event)" [max]="form.get('handBackTime')?.value"
                 [ngxMatDatetimePicker]="eventPickUpTime"
                 formControlName="pickUpTime"
                 matInput readonly>
          <mat-datepicker-toggle [for]="eventPickUpTime" matSuffix></mat-datepicker-toggle>
          <ngx-mat-datetime-picker #eventPickUpTime [color]="'primary'" [defaultTime]="[15,0,0]"
                                   [disableMinute]="false"
                                   [enableMeridian]="false" [hideTime]="false" [showSeconds]="false"
                                   [showSpinners]="true"
                                   [stepHour]="1" [stepMinute]="15" [touchUi]="true">
            <ng-template>
              <span>OK</span>
            </ng-template>
          </ngx-mat-datetime-picker>
          <mat-error *ngIf="showError('pickUpTime')">Bitte geben Sie eine valide Startzeit an.</mat-error>
        </mat-form-field>
`

Screenshot 2023-07-25 112502

**Pull request closed without merging**
