### PR TITLE
Upgrade to angular 14

### PR DESCRIPTION
**Pull request by MathewBerg**
There's no develop_angular14 to PR too so this is going against develop_angular13 to show what changes may be needed. Also set the version to 14.0.0 so that it mimics the angular pattern.

### CODE REVIEW

**Comment by Yirica** [comment]
Hi,
any update on this? I would like to upgrade our project to 14, but this component peers against ^13.0.1 :(

**Comment by alannsiqueira** [comment]
Any update?

**Comment by h2qutc** [comment]
Hi @MathewBerg, thank you for your support and your PR. 
A new version v8.0.0 supporting Angular 14 has been released. Feel free to check it out. 
I let your PR open by waiting for the feedbacks for v8.0.0.
Thank again for your support.

**Comment by MathewBerg** [comment]
Of course, glad to help @h2qutc. If you don't need my PR anymore I will close it, thanks again for updating the NPM package!

**Pull request closed without merging**
